interface Bank {
  name: string
  value: string
}

export const banks: Bank[] = [
  { name: 'Banco AV Villas', value: '1052' },
  { name: 'Banco Agrario', value: '1040' },
  { name: 'Bancamia S.A', value: '1059' },
  { name: 'Banco caja social', value: '1032' },
  { name: 'Banco Citibank', value: '1009' },
  { name: 'Banco Coopcentral', value: '1066' },
  { name: 'Banco Davivienda', value: '1051' },
  { name: 'Banco de Bogota', value: '1001' },
  { name: 'Banco de Occidente', value: '1023' },
  { name: 'Banco Falabella', value: '1062' },
  { name: 'Banco GNB Sudameris', value: '1012' },
  { name: 'Banco J.P Morgan Colombia S.A', value: '1071' },
  { name: 'Banco Pichincha S.A', value: '1060' },
  { name: 'Banco Popular', value: '1002' },
  { name: 'Banco Santander de Negocios', value: '1065' },
  { name: 'Banco Serfinanza', value: '1069' },
  { name: 'Banco W S.A', value: '1053' },
  { name: 'Bancoldex', value: '1031' },
  { name: 'Bancolombia', value: '1007' },
  { name: 'Bancoomeva', value: '1061' },
  { name: 'BBVA Colombia', value: '1013' },
  { name: 'Coltefinanciera S.A', value: '1370' },
  { name: 'Confiar Cooperativa Financiera', value: '1292' },
  { name: 'BAN100', value: '1558' },
  { name: 'Daviplata', value: '1551' },
  { name: 'DING Tecnipagos S.A', value: '1802' },
  { name: 'Giros y Finanzas', value: '1303' },
  { name: 'Iris', value: '1637' },
  { name: 'Itaú', value: '1014' },
  { name: 'Itaú antes Corpbanca', value: '1006' },
  { name: 'Lulo Bank', value: '1070' },
  { name: 'MOVII', value: '1801' },
  { name: 'NEQUI', value: '1507' },
  { name: 'Scotiabank Colpatria', value: '1019' },
  { name: 'Banco BTG Pactual', value: '1805' },
  { name: 'UALA', value: '1804' },
  { name: 'POWWI', value: '1803' },
  { name: 'COINK', value: '1812' },
  { name: 'RappiPay', value: '1811' },
  { name: 'BANCO MUNDO MUJER S.A', value: '1047' },
  { name: 'JFK COOPERATIVA FINANCIERA', value: '1286' },
  { name: 'BOLD COMPAÑIA DE FINANCIAMIENTO S.A', value: '1808' },
  { name: 'GLOBAL COLOMBIA 81 S.A', value: '1814' },
  { name: 'NU COLOMBIA COMPAÑIA DE FINANCIAMIENTO S.A', value: '1809' },
  { name: 'Aval Soluciones Digitalis S.A', value: '1897' },
  { name: 'PIBANK', value: '1560' }
]
