import { Providers } from './providers'
import { NavBarr, OrderModal } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Foodllowers-Kitchens',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body className='h-screen flex flex-col items-center'>
        <Providers>
          <NavBarr />
          <OrderModal />
          {children}
        </Providers>
      </body>
    </html>
  )
}
